# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License
# Pgpool-II PCP user authentication configuration
# Syntax: username:password_md5_hash

# Default pgpool user (password: pgpool)
pgpool:5f4dcc3b5aa765d61d8327deb882cf99

# Default postgres user (password: postgres)
postgres:a6f5d682ad0b20df7e34c141b8a1e66f
