# Copyright FreeCharts.
# SPDX-License-Identifier: MIT License
# Pgpool-II PCP user authentication configuration
# Syntax: username:password_md5_hash

# Default pgpool user (password: pgpool)
pgpool:ba777e4c2f15c11ea8ac3be7e0440aa0

